---
- name: Cleanup Vault | Remove Docker
  become: true
  become_user: "{{  rv_hashicorp_vault_os_user  }}"
  docker_container:
    name: "{{  rv_hashicorp_vault_os_docker_name  }}"
    state: absent

- name: Cleanup Vault | Remove Crop job
  cron:
    user: "{{  rv_hashicorp_vault_os_user  }}"
    name: "{{  rv_hashicorp_vault_os_cron_job_name  }}"
    state: absent

- name: Cleanup Vault | Remove Cron Setup Directory
  file:
    path: "{{  rv_hashicorp_vault_post_install_action_setup_auto_unseal_cron_dir  }}"
    state: absent

- name: Cleanup Vault | Remove Init Directory
  file:
    path: "{{  rv_hashicorp_vault_post_install_action_initialize_secrets_directory  }}"
    state: absent

- name: Cleanup Vault | Remove Data Directory
  file:
    path: "{{  rv_hashicorp_vault_os_data_directory  }}"
    state: absent
